--- 
abstract: apply roles to your Catalyst application-related classes
author: 
  - Hans Dieter Pearcey <hdp@cpan.org>
generated_by: Dist::Zilla::Plugin::MetaYaml version 1.004
license: perl
name: CatalystX-RelatedClassRoles
requires: 
  Catalyst::Runtime: 5.7
  Class::MOP: 0.80
  Moose: 0.73
  MooseX::Role::RelatedClassRoles: 0.002
version: 0.001
